import React from 'react';
import { motion } from 'framer-motion';
import { ShieldAlert, ExternalLink } from 'lucide-react';
import { Link } from 'react-router-dom';

interface AiDisclaimerBannerProps {
  agreed: boolean;
  onAgreementChange: (agreed: boolean) => void;
}

const AiDisclaimerBanner: React.FC<AiDisclaimerBannerProps> = ({ agreed, onAgreementChange }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: -8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="mb-6 rounded-xl border border-amber-200 dark:border-amber-700/60 bg-amber-50 dark:bg-amber-900/20 p-4"
      role="region"
      aria-label="AI Health Disclaimer"
    >
      <div className="flex items-start gap-3 mb-3">
        <ShieldAlert
          size={20}
          className="shrink-0 mt-0.5 text-amber-600 dark:text-amber-400"
          aria-hidden="true"
        />
        <div>
          <h3 className="text-sm font-semibold text-amber-800 dark:text-amber-300 mb-1">
            AI Health Disclaimer
          </h3>
          <p className="text-sm text-amber-700 dark:text-amber-400 leading-relaxed">
            This tool provides <strong>informational insights only</strong> — not a medical
            diagnosis. Results are generated by AI and may be inaccurate. Always consult a
            qualified doctor before making any health decisions.{' '}
            <Link
              to="/privacypolicy"
              className="inline-flex items-center gap-0.5 underline underline-offset-2 hover:text-amber-900 dark:hover:text-amber-200 transition-colors"
            >
              Privacy Policy
              <ExternalLink size={11} aria-hidden="true" />
            </Link>
          </p>
        </div>
      </div>

      <label className="flex items-center gap-2.5 cursor-pointer select-none group">
        <input
          type="checkbox"
          checked={agreed}
          onChange={(e) => onAgreementChange(e.target.checked)}
          className="w-4 h-4 rounded border-amber-400 dark:border-amber-600 text-amber-600 dark:text-amber-400
                     focus:ring-2 focus:ring-amber-500 focus:ring-offset-1 dark:focus:ring-offset-neutral-900
                     accent-amber-600 cursor-pointer"
          aria-describedby="disclaimer-description"
        />
        <span
          id="disclaimer-description"
          className="text-sm text-amber-800 dark:text-amber-300 group-hover:text-amber-900 dark:group-hover:text-amber-200 transition-colors"
        >
          I understand this is an AI tool and <strong>not</strong> a replacement for
          professional medical advice
        </span>
      </label>
    </motion.div>
  );
};

export default AiDisclaimerBanner;
